version: '3.8'

services:
  app:
    build: .
    user: node
    restart: unless-stopped
    ports:
      - 8031:8080
    environment:
      DB_HOST: 192.168.0.79
      DB_USER: aodevbot_user
      DB_PASSWORD: QOz9H5M5r@Rj[ZNs
      DB_NAME: aodevbot_dev
      DB_PORT: 3306
      TWITCH_USERNAME:
      TWITCH_CLIENT_ID:
      TWITCH_CLIENT_SECRET:
      SPOTIFY_CLIENT_ID:
      SPOTIFY_CLIENT_SECRET:
      DEBUG: false
      DEFAULT_TIMEZONE: 'America/Los_Angeles'
    working_dir: /home/node/app
    volumes:
      - './src:/home/node/app'
